#!/usr/bin/env bash
# Generate human-readable <release>-dod.md from <release>-dod.yaml.
# Usage: scripts/generate-dod-md.sh [release]
# If release is omitted, reads devdocs/plans/releases/CURRENT.
# Requires: yq (https://github.com/mikefarah/yq)

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RELEASES_DIR="$REPO_ROOT/devdocs/plans/releases"
CURRENT_FILE="$RELEASES_DIR/CURRENT"

if ! command -v yq >/dev/null 2>&1; then
  echo "generate-dod-md.sh requires yq. Install: brew install yq (macOS) or see https://github.com/mikefarah/yq"
  exit 1
fi

if [[ -n "$1" ]]; then
  RELEASE="$1"
else
  if [[ ! -f "$CURRENT_FILE" ]]; then
    echo "Missing $CURRENT_FILE and no release argument given"
    exit 1
  fi
  RELEASE=$(grep -v '^#' "$CURRENT_FILE" | grep -v '^[[:space:]]*$' | head -1)
fi
RELEASE=$(echo "$RELEASE" | xargs)
[[ -z "$RELEASE" ]] && { echo "Release is empty"; exit 1; }

DOD_YAML="$RELEASES_DIR/$RELEASE-dod.yaml"
DOD_MD="$RELEASES_DIR/$RELEASE-dod.md"

if [[ ! -f "$DOD_YAML" ]]; then
  echo "Missing $DOD_YAML"
  exit 1
fi

SOURCE_PLAN=$(yq '.source_plan' "$DOD_YAML")
echo "# Definition of Done: $RELEASE" > "$DOD_MD"
echo "" >> "$DOD_MD"
echo "Generated from \`$RELEASE-dod.yaml\`. Source plan: \`$SOURCE_PLAN\`. Do not edit this file by hand; run \`scripts/generate-dod-md.sh\` to regenerate." >> "$DOD_MD"
echo "" >> "$DOD_MD"
echo "Verify with: \`scripts/verify-dod.sh\`" >> "$DOD_MD"
echo "" >> "$DOD_MD"
echo "## Items" >> "$DOD_MD"
echo "" >> "$DOD_MD"

N=$(yq '.items | length' "$DOD_YAML")
for (( i=0; i<N; i++ )); do
  ID=$(yq ".items[$i].id" "$DOD_YAML")
  DESC=$(yq ".items[$i].description" "$DOD_YAML")
  SRC=$(yq ".items[$i].source" "$DOD_YAML")
  STATUS=$(yq ".items[$i].status" "$DOD_YAML")
  GAP_REASON=$(yq ".items[$i].gap_reason" "$DOD_YAML")
  if [[ "$STATUS" == "DONE" ]]; then
    echo "- [x] **$ID** — $DESC" >> "$DOD_MD"
  else
    if [[ -n "$GAP_REASON" && "$GAP_REASON" != "null" ]]; then
      echo "- [ ] **$ID** — $DESC  \`[GAP: $GAP_REASON]\`" >> "$DOD_MD"
    else
      echo "- [ ] **$ID** — $DESC" >> "$DOD_MD"
    fi
  fi
  echo "  - *Source:* $SRC" >> "$DOD_MD"
  echo "" >> "$DOD_MD"
done

echo "Regenerated $DOD_MD"
